# Generated by Django 4.1.1 on 2022-09-18 23:26

import biti.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('wallet', models.FloatField(default=0.0, verbose_name='Wallet funds')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
            },
            managers=[
                ('objects', biti.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('returns', models.IntegerField(verbose_name='Return multiples')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Int', 'INT'), ('Str', 'STR'), ('Bool', 'BOOL'), ('Float', 'FLOAT')], default='Str', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('product', models.ImageField(max_length=150, upload_to='trade/')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('returns', models.IntegerField(verbose_name='Return multiples')),
                ('start', models.IntegerField(verbose_name='Start Due Date')),
                ('maximum', models.IntegerField(verbose_name='End Due Date')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default=uuid.UUID('c9c6dc85-7baf-4edc-96d2-0b82ea16f584'), max_length=64)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_kgs', to=settings.AUTH_USER_MODEL, verbose_name='User KGS')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('product', models.ImageField(max_length=150, upload_to='invest/')),
                ('title', models.CharField(max_length=50)),
                ('start', models.IntegerField(verbose_name='Start Due Date')),
                ('end', models.IntegerField(verbose_name='End Due Date')),
                ('price', models.FloatField()),
                ('investment_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biti.investmentcountries', verbose_name='Investment Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
