# Generated by Django 4.1.1 on 2022-09-19 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biti', '0002_alter_kgs_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgs',
            name='product_type',
            field=models.CharField(choices=[('Kgs', 'KGS'), ('Trade', 'TRADE'), ('Invest', 'INVEST'), ('Partner', 'PARTNER')], default='Trade', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kgs',
            name='key',
            field=models.CharField(default=uuid.UUID('09fe7f9d-f2a2-4d78-8b03-b907d1957974'), max_length=64),
        ),
    ]
