# Generated by Django 4.1.1 on 2022-09-19 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biti', '0003_kgs_product_type_alter_kgs_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgs',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='kgs',
            name='key',
            field=models.CharField(default=uuid.UUID('490c2687-ca5e-49fd-901e-4d4e6ac71714'), max_length=64),
        ),
    ]
