# Generated by Django 4.1.1 on 2022-09-19 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biti', '0004_kgs_price_alter_kgs_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgs',
            name='key',
            field=models.CharField(default=uuid.UUID('96e912a1-8fa1-49a4-902e-97a8a2b7f9bd'), max_length=64),
        ),
    ]
