# Generated by Django 4.1.1 on 2022-09-19 18:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biti', '0007_alter_kgs_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgs',
            name='key',
            field=models.CharField(default=uuid.UUID('a1d39a60-65a5-4612-8516-b62727680605'), max_length=64),
        ),
    ]
