# Generated by Django 4.1.1 on 2022-09-19 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biti', '0008_alter_kgs_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invest',
            name='investment_location',
        ),
        migrations.AlterField(
            model_name='kgs',
            name='key',
            field=models.CharField(default=uuid.UUID('745c26bb-f51b-44e1-aabf-1b1cd65cadde'), max_length=64),
        ),
        migrations.AddField(
            model_name='invest',
            name='investment_location',
            field=models.ManyToManyField(to='biti.investmentcountries', verbose_name='Investment Locations'),
        ),
    ]
