# Generated by Django 4.1.1 on 2022-09-19 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biti', '0009_remove_invest_investment_location_alter_kgs_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invest',
            old_name='end',
            new_name='end_range',
        ),
        migrations.RenameField(
            model_name='invest',
            old_name='start',
            new_name='start_range',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='maximum',
            new_name='end_range',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='start',
            new_name='start_range',
        ),
        migrations.AlterField(
            model_name='kgs',
            name='key',
            field=models.CharField(default=uuid.UUID('4bf980a4-45a7-439e-bcf4-b9a112333888'), max_length=64),
        ),
    ]
