# Generated by Django 4.1.1 on 2022-09-20 09:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biti', '0011_alter_investmentcountries_options_alter_kgs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgs',
            name='key',
            field=models.CharField(default=uuid.UUID('a8201423-73cd-40ad-bd7f-00c6ce66c352'), max_length=64),
        ),
    ]
