# Generated by Django 4.1.1 on 2022-09-20 09:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('biti', '0012_alter_kgs_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgs',
            name='key',
            field=models.CharField(default=uuid.UUID('136e87de-5c38-47ad-9624-e4db4d9d9f8f'), max_length=64),
        ),
    ]
