# Generated by Django 4.1.1 on 2022-09-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_purchase_buyer_alter_purchase_invest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.URLField(blank=True, null=True),
        ),
    ]
