# Generated by Django 4.1.1 on 2022-09-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_purchase_price_purchase_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='product',
            new_name='image_url',
        ),
    ]
